#! /bin/sh

/bin/mount -o remount,ro /dev/root /
mount -t proc none /proc
mount -t sysfs none /sys

echo /sbin/mdev > /proc/sys/kernel/hotplug

/sbin/mdev -s

/bin/mount -a

mount -t tmpfs -o size=700m none /root
chmod go+rw /dev/null         
chmod go+r /dev/random        
chmod go+r /dev/urandom
chmod ugo+rw /dev/tty

mkfs.ext2 /dev/ram0  >/dev/null
mkfs.ext2 /dev/ram1  >/dev/null
mkfs.ext2 /dev/ram2  >/dev/null
mkfs.ext2 /dev/ram3  >/dev/null
mkfs.ext2 /dev/ram4  >/dev/null
mkfs.ext2 /dev/ram5  >/dev/null
mkfs.ext2 /dev/ram6  >/dev/null

/bin/mount -t ext2 dev/ram0 /var
mkdir /var/log
mkdir /var/db
touch /var/db/dhcpd.leases
mkdir /var/ftp
mkdir /var/empty 
mkdir /var/run 
mkdir /var/run/wpa_supplicant 
mkdir /var/run/hostapd
mkdir /var/log/lastlog 
mkdir /var/tmp 
mkdir /var/local 
mkdir /var/lib 
mkdir /var/lock 
mkdir /var/spool 
mkdir /var/spool/cron
mkdir /var/spool/cron/crontabs 
mkdir /var/state

/bin/mount -t ext2 /dev/ram1 /tmp
chmod 777 /tmp

mount -t ext2 /dev/ram5 /mnt
cp -aR /dev/* /mnt
umount /mnt 
mount -t ext2 /dev/ram5 /dev

# video / drm device
mkdir /dev/dri
mknod /dev/dri/card0 c 226 0
mknod /dev/dri/controlD64 c 226 64
mknod /dev/dri/renderD128 c 226 128
chgrp video /dev/dri/card0
chgrp video /dev/dri/controlD64
chgrp video /dev/dri/renderD128
chmod g+wr  /dev/dri/card0
chmod g+wr  /dev/dri/controlD64
chmod g+wr  /dev/dri/renderD128

mkdir /dev/pts
mount devpts /dev/pts -t devpts
chmod go+rw /dev/null                                                         
chmod go+r /dev/random                                                        
chmod go+r /dev/urandom                                                       
chmod ugo+rw /dev/tty

mount -t ext2 /dev/ram2 /mnt
cp -aR /etc/* /mnt
umount /mnt 
mount -t ext2 /dev/ram2 /etc 

mount -t ext2 /dev/ram3 /mnt
cp -aR /home/* /mnt
umount /mnt 
mount -t ext2 /dev/ram3 /home 
chmod -R 777 /home
chmod oug-w /home

PATH=/usr/bin:/bin:/sbin:/usr/sbin
export LD_LIBRARY_PATH=/lib:/lib64:/usr/lib
#hd-idle -a sda -i 720

ifconfig eth0 up
udhcpc &

inetd

/sbin/sshd

ifconfig lo 127.0.0.1 up
#smbd

#/sbin/dhcpd -cf /etc/dhcpd.conf
#ntpdate  ntp.univ-lyon1.fr canon.inria.fr ntp1.tuxfamily.net
klogd
syslogd
#crond
#crontab /etc/crontab
httpd -h /home/www
vsftpd &
#wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf
hostapd -d /etc/hostapd.conf &
